import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  count: 0,
};

const slice1 = createSlice({
  name: 'counter',
  initialState, // Initial state
  reducers: {
    increment: (state) => {
      state.count += 1; // Increase count
    },
    decrement: (state) => {
      state.count -= 1; // Decrease count
    },
  },
});

// Export the actions generated by createSlice
export const { increment, decrement } = slice1.actions;

// Export the reducer for the store
export default slice1.reducer;
